config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/addcourse',  to: 'courses#new'
  post  '/addcourse',  to: 'courses#create'
  get   '/addcategory', to: 'categories#new'
  post  '/addcategory', to: 'categories#create'
  get   '/addlocation', to: 'locations#new'
  post  '/addlocation', to: 'locations#create'
  post '/courses/like', to:'courses#hitlike'
  post '/courses/dislike', to:'courses#hitdislike'
  post '/courses/vote', to:'courses#resetvote'
  post '/feedback', to:'feedbacks#create'

  
  resources :users
  resources :courses
  resources :categories
  resources :locations
end

app/models/location.rb
class Location < ApplicationRecord
    has_many :courses
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def index
    @locations = Location.all
  end
  
  def new
    @categories = Category.all 
    @locations = Location.all
    @location = Location.new
  end
  
  def show
    @categories = Category.all 
    @locations = Location.all
    @courses = Course.all
    @location = Location.find(params[:id])
  end
  
  def create
    @categories = Category.all 
    @locations = Location.all
    @location = Location.new(location_params)
    if @location.save
      flash[:success] = "Created new Location!"
      redirect_to(root_url)
    else
      render 'new'
    end
    
  end

  private
  
    def location_params
      params.require(:location).permit(:name)
    end
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/locations/_menu.html.erb
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Location <b class="caret"></b>
          </a>
          
          <ul class="dropdown-menu">
            <% @locations.each do |location| %>
              <li><%= link_to location.name, location %></li> 
            <% end %>
            <li class="divider"></li>
              <li><%= link_to "Create location", addlocation_path %></li>
          </ul>  
        </li> 

app/views/locations/index.html.erb
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Location <b class="caret"></b>
          </a>
          
          <ul class="dropdown-menu">
            <% @locations.each do |location| %>
              <li><%= link_to location.name, '#' %></li> 
            <% end %>
            <li class="divider"></li>
              <li><%= link_to "Create location", addlocation_path %></li>
          </ul>  
        </li> 

app/views/locations/new.html.erb
<% provide(:title, 'Create new location') %>
<% provide(:button_text, 'Add new location') %>
<h1>Add new location</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/locations/show.html.erb
<% provide(:title, @location.name) %>

<div style="text-align:center">
    <h1>Courses scheduled in location <%= @location.name %> </h1>
  <hr>
</div>

    <div class="tab">
      <ul class="nav navbar-nav">
       
       <li><a href="/courses">Course</a></li>
       <li><a href="/users">Coordinator</a></li>
      </ul>
    </div>
    
    
  </div>
  
   

<ul class="courses">
  <% @location.courses.each do |course| %>
  <div align="left">
   <div style="display:flex;margin:40px;">
    <div style="display:flex;flex-direction:column;width:200px">
      
    <li>
    <%= link_to gravatar_for(course.user, size: 150), course.user %>
    </li>
    <h2>
     Coordinator name: <%= link_to course.user.name, course.user %>
    </h2>
      
    </div>

    
    <div class="border" style="padding:30px;width:500px;background-color:lightgrey; ">
    
    <h2>
      Course name:
      <%= link_to course.name, course %>
    </h2>
    <h2>
        Course category:
        <%= link_to course.category.name, course.category%>
    </h2>
    <h2>
        Course location:
        <%= link_to course.location.name, course.location%>
    </h2>
    <h2>
        Created at:
        <%= link_to course.created_at, course%>
    </h2>
    
    

  <div style="text-align:right">
        <% if logged_in? %>
          <%= link_to "<icon class='glyphicon glyphicon-thumbs-up' style='margin-right:5px;'></icon>".html_safe,
          courses_like_path(:course_name =>  course.name), :method => :post %>
        <%= course.like %>
          <%= link_to "<icon class='glyphicon glyphicon-thumbs-down' style='margin-right:5px;'></icon>".html_safe,
          courses_dislike_path(:course_name =>  course.name), :method => :post %>
        <%= course.dislike %>
        <% else %>  
            <%= link_to "<icon class='glyphicon glyphicon-thumbs-up' style='margin-right:5px;'></icon>".html_safe %>
        <%= course.like %>
            <%= link_to "<icon class='glyphicon glyphicon-thumbs-down' style='margin-right:5px;'></icon>".html_safe %>
        <%= course.dislike %>
        <% end %>

       </div>
  </div>
  </div>
        <% if logged_in? %>
        <% if current_user.admin? || current_user?(course.user) %>
            <%= link_to "Edit", edit_course_path(course), class: "btn btn-primary" %>
        <% end %>
        <% if current_user.admin? %>
            <%= link_to "Delete", @course, method: :delete, class: "btn btn-primary",
                                       data: { confirm: "You sure?" } %>
            <%= link_to "Reset votes", courses_vote_path(:course_name =>  course.name), :method => :post, class: "btn btn-primary",
                                       data: { confirm: "You sure?" } %>
        <% end %>   
        <% end %>
  <% end %>
</ul>