config/routes.rb
Rails.application.routes.draw do
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/addcourse',  to: 'courses#new'
  post  '/addcourse',  to: 'courses#create'
  get   '/addcategory', to: 'categories#new'
  post  '/addcategory', to: 'categories#create'
  get   '/addlocation', to: 'locations#new'
  post  '/addlocation', to: 'locations#create'
  post '/courses/like', to:'courses#hitlike'
  post '/courses/dislike', to:'courses#hitdislike'
  post '/courses/vote', to:'courses#resetvote'
  post '/feedback', to:'feedbacks#create'

  
  resources :users
  resources :courses
  resources :categories
  resources :locations
end

app/views/layouts/_footer.html.erb
<footer class="footer">




  <nav>
    <ul>
        <div class="row">
        <div class="column">
         <div align="left",style="width:20%;">
            <h4><strong>Contact us</strong></h3>
            <%= form_for(:feedback, url: feedback_path) do |f| %>
                <%= f.text_area :body ,:style=>"
                border-color: #878787;border-style: solid;border-top-width: 0px;
                border-right-width: 0px;border-bottom-width: 1px;
                border-left-width: 0px;background:inherit;" %>
                <br>
                <%= f.submit "Send", class:"btn" %>
            <% end %>
            <div style="margin:20px 0;">
            <p style="margin:0">Tel:0123456789</p>
            <p style="margin:0">Fax:0123456</p>
            <p style="margin:0">s3553665@rmit.edu.au</p>  
         </div>
        </div>   
        </div> 



        <div class="column">
        <ul class=" general-inquires">
            <h4><strong>General inquires</strong></h3>
            <li><a href="https://www.rmit.edu.au/contact/staff-contacts/academic-staff/s/song-dr-andy">Andy Song</a></li>
            <li><a href="javascript">Junliang Jiang</a></li>
            <li><a href="javascript">Ali</a></li>

        </ul>
        </div
        </div>
        
        <div class="column">
          <ul class=" useful-links">
            <h4><strong>Useful Links</strong></h3>
            <li><a href="https://www.rmit.edu.au/study-with-us">RMIT Course</a></li>
            <li><a href="https://www.rmit.edu.au/students/support-and-facilities/it-services-for-students/service-and-support-centre">RMIT Help Desk</a></li>
            <li><a href="https://www.rmit.edu.au/study-with-us/international-students">RMIT International</a></li>
           </ul>
        </div>

        <div class="column">
        <ul class="social-media-list">
            <h4><strong>Media</strong></h3>
            <li><a href="https://twitter.com/"><img src="https://unpkg.com/simple-icons@latest/icons/twitter.svg" alt="Twitter" title="Twitter"></a></li>
            <li><a href="https://github.com/"><img src="https://unpkg.com/simple-icons@latest/icons/github.svg" alt="GitHub" title="GitHub"></a></li>
            <li><a href="https://www.facebook.com/"><img src="https://unpkg.com/simple-icons@1.9.27/icons/facebook.svg" alt="Facebook" title="Facebook"></a></a></li>
            <li><a href="https://www.youtube.com/"><img src="https://unpkg.com/simple-icons@latest/icons/youtube.svg" alt="YouTube" title="YouTube"></a></li>
            <li><a href="https://www.instagram.com/"><img src="https://unpkg.com/simple-icons@1.9.27/icons/instagram.svg" alt="Instagram" title="Instagram"></a></li>
            <li><a href="https://www.skype.com/en/"><img src="https://unpkg.com/simple-icons@1.9.27/icons/skype.svg" alt="Skype" title="Skype"></a></li>
        </ul>
        </div>
        </div>
    </ul>
  </nav>
</footer> 

app/views/layouts/_header.html.erb
  <div class="container">
    <% if logged_in? %>
    <%= link_to "Your Course App", courses_path, id: "logo" %>  
    <% else %>
    <%= link_to "Your Course App", root_path, id: "logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        
        <%= render 'categories/menu' %>
        <%= render 'locations/menu' %>
        <% if logged_in? %>
          <li><%= link_to "New Course", addcourse_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %>  <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit account", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>

        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>